# DockerFile for IITB OCR API
# Run the file

FROM krishna0512/tensorflow-opencv:1.8.0

RUN pip install python-doctr
RUN pip install "python-doctr[torch]"

!pip install -e ./doctr/.
!pip install -e ./doctr/.[torch]

RUN apt update && apt install -y curl

ENV PYTHONUNBUFFERED 1

WORKDIR /app